path: '/Users/sebastianessink/Dropbox (MIT)/niw/'
#floats: ['7700b','7701b']
floats: ['7700b','7701b','7779a','7780b','7781a','7783a','7784b',
  '7785b','7786a','7786b','7787a','7788a']
groups: ['a','b']
resample_period: '3h'
filter_period: 2
