path: '/Users/sebastianessink/Dropbox (MIT)/niw/'
#floats: ['7700b','7701b']
floats: ['7779a', '7781a', '7783a', '7786a', '7787a', '7788a',
    '7700b', '7701b','7780b', '7784b', '7785b', '7786b']
groups: ['a','b']
resample_period: '1h'
filter_period: 2
